/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol iGaia_GrapeHost
- (int)SendMsgToHost:(struct tGaia_BackwardControlMessage *)arg1 rspBuff:(struct tGaia_BackwardControlMessage *)arg2 timeoutSec:(unsigned char)arg3;
@end

