/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface CHBPie2DType : NSObject
{
}

+ (void)readWithState:(id)arg1 chartType:(id)arg2;
+ (id)chdChartTypeWithState:(id)arg1;

@end

