/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "EDKeyedObject.h"

@class CHDDataLabel, CHDMarker, OADGraphicProperties;

__attribute__((visibility("hidden")))
@interface CHDDataValueProperties : NSObject <EDKeyedObject>
{
    CHDDataLabel *mDataLabel;
    CHDMarker *mMarker;
    unsigned int mDataValueIndex;
    OADGraphicProperties *mGraphicProperties;
}

+ (id)dataValueProperties;
- (void)setMarker:(id)arg1;
- (id)marker;
- (void)setGraphicProperties:(id)arg1;
- (id)graphicProperties;
- (void)setDataValueIndex:(unsigned int)arg1;
- (unsigned int)dataValueIndex;
- (void)setDataLabel:(id)arg1;
- (id)dataLabel;
- (int)key;
- (void)dealloc;
- (id)shallowCopyWithIndex:(int)arg1;
- (id)init;

@end

