/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/CHDSeries.h>

__attribute__((visibility("hidden")))
@interface CHDPie2DSeries : CHDSeries
{
    int mExplosion;
}

- (void)setExplosion:(int)arg1;
- (int)explosion;
- (id)init;

@end

