/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/CHDAxis.h>

__attribute__((visibility("hidden")))
@interface CHDSeriesAxis : CHDAxis
{
    int mLabelFrequency;
}

- (void)setLabelFrequency:(int)arg1;
- (int)labelFrequency;
- (id)initWithResources:(id)arg1;

@end

