/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/EMCellStyle.h>

@class OADDrawable;

__attribute__((visibility("hidden")))
@interface CMDrawableStyle : EMCellStyle
{
    OADDrawable *mDrawable;
}

- (void)addPositionUsingOffsets:(struct CGRect)arg1;
- (void)addPositionProperties:(struct CGRect)arg1;

@end

