/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface CMGlobalCache : NSObject
{
}

+ (void)releaseGlobalCache;
+ (void)initGlobalCache;
+ (id)drawableElementCache;
+ (id)cssStylesheetCache;
+ (id)borderWidthCache;
+ (id)borderStyleCache;
+ (id)lengthPropertyCache;
+ (id)colorPropertyCache;

@end

