/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class SFUZipEntry;

__attribute__((visibility("hidden")))
@interface CPBundleResourcePackageEntry : NSObject
{
    SFUZipEntry *mZipEntry;
    struct _xmlDoc *mXmlDocument;
}

- (struct _xmlDoc *)xmlDocument;
- (id)data;
- (void)dealloc;
- (id)initWithZipEntry:(id)arg1;

@end

