/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/CPTracing.h>

__attribute__((visibility("hidden")))
@interface CPExportTracing : CPTracing
{
}

- (void)stopWriting;
- (void)startWriting;
- (void)stopExporting;
- (void)startExporting;
- (void)dealloc;
- (id)initWithFilename:(id)arg1;

@end

