/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface CPMessagePlaceholderInfo : NSObject
{
    id mKey;
    BOOL mInUse;
}

- (void)setInUse:(BOOL)arg1;
- (BOOL)isInUse;
- (id)key;
- (void)dealloc;
- (id)init;

@end

