/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface EBTextBox : NSObject
{
}

+ (void)writeTextBox:(id)arg1 shape:(id)arg2 toXlGraphicsInfo:(struct XlGraphicsInfo *)arg3 state:(id)arg4;
+ (void)writeTextRotationFromShape:(id)arg1 toXlGraphicsInfo:(struct XlGraphicsInfo *)arg2 state:(id)arg3;
+ (id)edTextBoxFromXlGraphicsInfo:(struct XlGraphicsInfo *)arg1 edResources:(id)arg2;

@end

