/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface EDComment : NSObject
{
    _Bool mVisible;
    int mRowIndex;
    int mColumnIndex;
}

- (void)setColumnIndex:(int)arg1;
- (int)columnIndex;
- (void)setRowIndex:(int)arg1;
- (int)rowIndex;
- (void)setVisible:(_Bool)arg1;
- (_Bool)isVisible;

@end

