/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/CMMapper.h>

__attribute__((visibility("hidden")))
@interface EMSheetMapper : CMMapper
{
}

- (struct CGSize)preprocessSizeWithState:(id)arg1;
- (int)preprocessHeightWithState:(id)arg1;
- (int)preprocessWidthWithState:(id)arg1;
- (struct CGSize)adjustedSize;
- (int)height;
- (int)width;

@end

