/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/CMState.h>

@class EDSheet, EDWorkbook;

__attribute__((visibility("hidden")))
@interface EMState : CMState
{
    EDWorkbook *_workbook;
    EDSheet *_currentSheet;
}

@property EDSheet *currentSheet; // @synthesize currentSheet=_currentSheet;
@property(retain) EDWorkbook *workbook; // @synthesize workbook=_workbook;
- (void)dealloc;

@end

