/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/EDBorder.h>

__attribute__((visibility("hidden")))
@interface EPBorder : EDBorder
{
    int mPrecedence;
}

+ (id)borderWithBorder:(id)arg1 precedence:(int)arg2 resources:(id)arg3;
- (int)precedence;
- (BOOL)isEqualToBorder:(id)arg1;
- (id)initWithBorder:(id)arg1 precedence:(int)arg2 resources:(id)arg3;

@end

