/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/MFPEffect.h>

__attribute__((visibility("hidden")))
@interface MFPColorBalanceEffect : MFPEffect
{
    long mCyanRed;
    long mMagentaGreen;
    long mYellowBlue;
}

+ (id)GUID;
- (id)initWithCyanRed:(long)arg1 magentaGreen:(long)arg2 yellowBlue:(long)arg3;

@end

