/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/MFPEffect.h>

__attribute__((visibility("hidden")))
@interface MFPHueSaturationLightnessEffect : MFPEffect
{
    long mHueChange;
    long mSaturationChange;
    long mLightnessChange;
}

+ (id)GUID;
- (id)initWithHueChange:(long)arg1 saturationChange:(long)arg2 lightnessChange:(long)arg3;

@end

