/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface MFPPath : NSObject
{
    struct CGPath *mPath;
}

- (struct CGPath *)path;
- (void)dealloc;
- (id)initWithPath:(struct CGPath *)arg1;

@end

