/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/MFPEffect.h>

__attribute__((visibility("hidden")))
@interface MFPTintEffect : MFPEffect
{
    long mHue;
    long mAmount;
}

+ (id)GUID;
- (id)initWithHue:(long)arg1 amount:(long)arg2;

@end

