/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol OABColorPropertiesManager <NSObject>
- (struct EshBlip *)fillBlipDataReference;
- (struct EshColor)shadowColor;
- (struct EshColor)strokeBgColor;
- (struct EshColor)strokeFgColor;
- (BOOL)isStroked;
- (struct EshColor)fillBgColor;
- (struct EshColor)fillFgColor;
- (BOOL)isFilled;
@end

