/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "OABFillPropertiesManager.h"

__attribute__((visibility("hidden")))
@interface OABFillPropertiesManager : NSObject <OABFillPropertiesManager>
{
    const struct EshFill *mFill;
    int mShapeType;
    id <OABPropertiesManager> mMasterManager;
}

- (id)fillBlipName;
- (struct EshBlip *)fillBlipDataReference;
- (unsigned long)fillBlipID;
- (const struct EshTablePropVal<EshGradientStop> *)fillGradientColors;
- (long)fillFocusBottom;
- (long)fillFocusRight;
- (long)fillFocusTop;
- (long)fillFocusLeft;
- (long)fillFocus;
- (long)fillAngle;
- (long)fillBgAlpha;
- (long)fillFgAlpha;
- (int)fillType;
- (struct EshColor)shadowColor;
- (struct EshColor)strokeBgColor;
- (struct EshColor)strokeFgColor;
- (BOOL)isStroked;
- (struct EshColor)fillBgColor;
- (struct EshColor)fillFgColor;
- (BOOL)isFilled;
- (void)dealloc;
- (id)initWithFill:(const struct EshFill *)arg1 shapeType:(int)arg2 masterShape:(struct EshShape *)arg3;

@end

