/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/OADBulletProperties.h>

@class OADBlipRef;

__attribute__((visibility("hidden")))
@interface OADImageBulletProperties : OADBulletProperties
{
    OADBlipRef *mImage;
}

- (BOOL)isEqual:(id)arg1;
- (id)image;
- (void)dealloc;
- (id)initWithBlipRef:(id)arg1;

@end

