/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/OADMovie.h>

@class NSURL;

__attribute__((visibility("hidden")))
@interface OADLinkedMediaFile : OADMovie
{
    NSURL *mUrl;
}

@property(retain) NSURL *url; // @synthesize url=mUrl;
- (void)dealloc;

@end

