/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/OADLineJoin.h>

__attribute__((visibility("hidden")))
@interface OADRoundLineJoin : OADLineJoin
{
}

+ (id)defaultProperties;
- (id)initWithDefaults;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

