/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/OADTextRun.h>

@class NSMutableString;

__attribute__((visibility("hidden")))
@interface OADRegularTextRun : OADTextRun
{
    NSMutableString *mText;
}

- (id)text;
- (BOOL)isEmpty;
- (void)dealloc;
- (id)init;

@end

