/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class OADCharacterProperties;

__attribute__((visibility("hidden")))
@interface OADTextRun : NSObject
{
    OADCharacterProperties *mProperties;
}

- (void)removeUnnecessaryOverrides;
- (void)setProperties:(id)arg1;
- (id)properties;
- (BOOL)isEmpty;
- (void)dealloc;
- (id)init;

@end

