/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/OADProperties.h>

__attribute__((visibility("hidden")))
@interface ODDLayoutVariablePropertySet : OADProperties
{
    int mDirection;
    BOOL mHasDirection;
}

+ (id)defaultProperties;
- (BOOL)hasDirection;
- (void)setDirection:(int)arg1;
- (int)direction;
- (id)initWithDefaults;

@end

