/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface ODDShapeAdjustment : NSObject
{
    unsigned int mIndex;
    double mValue;
}

- (void)setValue:(double)arg1;
- (double)value;
- (void)setIndex:(unsigned int)arg1;
- (unsigned int)index;

@end

