/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class OAXDrawingState;

__attribute__((visibility("hidden")))
@interface ODXState : NSObject
{
    OAXDrawingState *mOfficeArtState;
}

- (id)officeArtState;
- (void)dealloc;
- (id)initWithOfficeArtState:(id)arg1;

@end

