/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/PDCommonBehaviorData.h>

__attribute__((visibility("hidden")))
@interface PDAnimateRotateBehavior : PDCommonBehaviorData
{
    double mTo;
    double mFrom;
    double mBy;
}

- (void)setBy:(double)arg1;
- (double)by;
- (void)setFrom:(double)arg1;
- (double)from;
- (void)setTo:(double)arg1;
- (double)to;
- (id)init;

@end

