/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <OfficeImport/PDCommonBehaviorData.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface PDAnimateTimeBehavior : PDCommonBehaviorData
{
    NSMutableArray *mTimeAnimateValues;
}

- (void)addTimeAnimateValue:(id)arg1;
- (id)timeAnimateValueAtIndex:(int)arg1;
- (int)timeAnimateValueCount;
- (void)dealloc;
- (id)init;

@end

