/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface SFUZipFreeSpaceEntry : NSObject
{
    unsigned long long offset;
    unsigned long long length;
}

- (int)compareByOffset:(id)arg1;

@end

