/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface TSUFormatReferenceObject : NSObject
{
    CDStruct_95e644ef mFormatStruct;
}

- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (CDStruct_95e644ef)getFormatStruct;
- (id)initWithTSUFormatFormatStruct:(CDStruct_95e644ef)arg1;
- (id)init;

@end

