/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, WDDocument, WDListDefinition;

__attribute__((visibility("hidden")))
@interface WDListDefinitionTable : NSObject
{
    NSMutableArray *mListDefinitions;
    struct __CFDictionary *mListDefinitionMap;
    unsigned int mNextIdIndex;
    WDDocument *mDocument;
    WDListDefinition *mLastKnownGoodListDefinition;
}

- (id)definitionWithId:(int)arg1;
- (id)addDefinition:(int)arg1;
- (id)addDefinition;
- (id)definitionAt:(int)arg1;
- (int)definitionCount;
- (id)document;
- (void)dealloc;
- (id)initWithDocument:(id)arg1;
- (void)setLastKnowGoodListDefinition:(id)arg1;
- (int)nextId;

@end

