/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, WDDocument, WDListDefinition;

__attribute__((visibility("hidden")))
@interface WDList : NSObject
{
    NSMutableArray *mLevelOverrides;
    WDDocument *mDocument;
    int mIndex;
    WDListDefinition *mListDefinition;
}

- (id)initWithDocument:(id)arg1 listDefinition:(id)arg2;
- (int)listId;
- (void)setIndex:(int)arg1;
- (int)index;
- (id)levelOverrides;
- (id)addLevelOverride;
- (id)levelOverrideAt:(int)arg1;
- (int)levelOverrideCount;
- (id)listDefinition;
- (id)document;
- (void)dealloc;

@end

