/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, WDDocument;

__attribute__((visibility("hidden")))
@interface WDRevisionAuthorTable : NSObject
{
    NSMutableArray *mAuthors;
    WDDocument *mDocument;
}

- (int)authorAddLookup:(id)arg1;
- (void)addAuthor:(id)arg1;
- (id)authorAt:(int)arg1;
- (int)authorCount;
- (id)authors;
- (void)dealloc;
- (id)initWithDocument:(id)arg1;

@end

