/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface ML3QueryResultSet_BackingStore : NSObject
{
    vector_6f037ce7 _persistentIDs;
    struct vector<unsigned char, std::allocator<unsigned char>> _sections;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)backingStoreByRemovingPersistentIDs:(const unordered_set_a245ffee *)arg1;
- (void)enumerateSectionsUsingBlock:(id)arg1;
- (BOOL)containsPersistentIDs:(const unordered_set_a245ffee *)arg1;
- (void)enumeratePersistentIDsUsingBlock:(id)arg1;
- (long long)persistentIDAtIndex:(unsigned int)arg1;
@property(readonly, nonatomic) unsigned int count;

@end

