/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface MLSQLiteConnection_RegisteredFunction : NSObject
{
    NSString *_name;
    int _argumentCount;
}

- (void).cxx_destruct;
- (void)registerOnDB:(struct sqlite3 *)arg1;

@end

