/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface MLSQLiteConnection_RegisteredModule : NSObject
{
    const struct sqlite3_module *_moduleMethods;
    NSString *_name;
    void *_context;
    id _contextReleaseBlock;
}

@property(nonatomic) void *context; // @synthesize context=_context;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) id contextReleaseBlock; // @synthesize contextReleaseBlock=_contextReleaseBlock;
- (void).cxx_destruct;
- (void)registerOnConnection:(id)arg1;

@end

