/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <SportsTrainer/STValueUnitLabel.h>

@interface STRunTimeLabel : STValueUnitLabel
{
}

- (void)setRunTime:(double)arg1;

@end

