/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class _WebSafeForwarder;

__attribute__((visibility("hidden")))
@interface _WebSafeAsyncForwarder : NSObject
{
    _WebSafeForwarder *_forwarder;
}

- (id)methodSignatureForSelector:(SEL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)initWithForwarder:(id)arg1;

@end

