/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface WebDeviceOrientationInternal : NSObject
{
    struct RefPtr<WebCore::DeviceOrientation> m_orientation;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithCoreDeviceOrientation:(PassRefPtr_ce175d97)arg1;

@end

