/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "WebDocumentText.h"

@protocol WebDocumentSelection <WebDocumentText>
- (id)selectionView;
- (struct CGRect)selectionImageRect;
- (struct CGImage *)selectionImageForcingBlackText:(BOOL)arg1;
- (struct CGRect)selectionRect;
- (id)selectionTextRects;
@end

