/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "WebFormSubmissionListener.h"
#import "WebPolicyDecisionListener.h"

__attribute__((visibility("hidden")))
@interface WebFramePolicyListener : NSObject <WebPolicyDecisionListener, WebFormSubmissionListener>
{
    struct Frame *m_frame;
}

+ (void)initialize;
- (void)continue;
- (void)use;
- (void)download;
- (void)ignore;
- (void)receivedPolicyDecision:(int)arg1;
- (void)finalize;
- (void)dealloc;
- (void)invalidate;
- (id)initWithWebCoreFrame:(struct Frame *)arg1;

@end

