/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class WebFrameView;

__attribute__((visibility("hidden")))
@interface WebFramePrivate : NSObject
{
    struct Frame *coreFrame;
    WebFrameView *webFrameView;
    struct WebScriptDebugger *scriptDebugger;
    id internalLoadDelegate;
    BOOL shouldCreateRenderers;
    BOOL includedInWebKitStatistics;
    BOOL isCommitting;
    BOOL isSingleLine;
}

- (void)setWebFrameView:(id)arg1;
- (void)finalize;
- (void)dealloc;

@end

