/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <iWorkImport/GQDWPStorage.h>

@class GQDWPLayoutStorage;

__attribute__((visibility("hidden")))
@interface GQDWPBodyStorage : GQDWPStorage
{
    GQDWPLayoutStorage *mFootnotes;
}

- (void)dealloc;
- (struct __CFArray *)body;
- (id)footnotes;

@end

