/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class GQDDrawable;

__attribute__((visibility("hidden")))
@interface GQDWPAttachment : NSObject
{
    GQDDrawable *mDrawable;
}

- (id)drawable;
- (void)dealloc;

@end

