/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SSDownloadQueueObserver <NSObject>
- (void)downloadQueue:(id)arg1 changedWithRemovals:(id)arg2;

@optional
- (void)downloadQueueNetworkUsageChanged:(id)arg1;
- (void)downloadQueue:(id)arg1 downloadStatusChangedAtIndex:(int)arg2;
@end

