/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol CKBalloonViewDelegate <NSObject>
- (void)balloonDidFinishDataDetectorAction:(id)arg1;
- (void)balloonWillResignFirstResponder:(id)arg1;
- (void)restoreBalloonStateAfterRotation:(id)arg1;
- (struct CGRect)clippedTargetRectForBalloon:(id)arg1;
@end

