/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSAttributedString, UIColor, UIFont;

@protocol CKTextBalloonContentView <NSObject>
@property(nonatomic) int textAlignment;
@property(nonatomic) struct CGSize shadowOffset;
@property(retain, nonatomic) UIColor *shadowColor;
@property(retain, nonatomic) UIColor *textColor;
@property(retain, nonatomic) UIFont *font;
@property(copy, nonatomic) NSAttributedString *attributedText;

@optional
@property(nonatomic) id <CKTextInteractionDelegate> interactionDelegate;
- (void)prepareForReuse;
@end

