/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "IMService.h"

@interface IMService (CKAdditions)
- (int)__ck_maxRecipientCount;
- (id)__ck_displayName;
- (BOOL)__ck_isSMS;
- (BOOL)__ck_isiMessage;
@end

