/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol PLCameraSettingsViewDelegate <NSObject>
- (void)shouldEnterPanorama;
- (void)gridSettingDidChange:(BOOL)arg1;
- (void)HDRSettingDidChange:(BOOL)arg1;
@end

