/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UITextView.h"

@interface PLCommentTextView : UITextView
{
    BOOL _contentOffsetLocked;
}

@property(nonatomic) BOOL contentOffsetLocked; // @synthesize contentOffsetLocked=_contentOffsetLocked;
- (void)setContentOffset:(struct CGPoint)arg1 animated:(BOOL)arg2;
- (void)setContentOffset:(struct CGPoint)arg1;

@end

