/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <DataDetectorsUI/DDTelephoneNumberAction.h>

__attribute__((visibility("hidden")))
@interface DDCallAction : DDTelephoneNumberAction
{
}

- (void)perform;
- (id)localizedName;

@end

