/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TICompiledCollatorFile : NSObject
{
    int m_descriptor;
    char *m_mappedFile;
    long long m_length;
    NSString *m_path;
}

+ (struct UCollator *)createCollatorWithType:(int)arg1;
+ (id)sharedCollatorFile;
- (struct UCollator *)createCollatorWithType:(int)arg1;
- (void)dealloc;
- (id)initWithPath:(id)arg1 error:(unsigned int *)arg2;

@end

