/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <TextInput/TIKeyboardInputManagerZephyr.h>

__attribute__((visibility("hidden")))
@interface TIKeyboardInputManager_da : TIKeyboardInputManagerZephyr
{
}

- (void)setCollatorLocale;
- (struct TIInputManagerZephyr *)initImplementation;

@end

