/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class SSSQLiteDatabase;

__attribute__((visibility("hidden")))
@interface SSKeyValueStoreDatabase : NSObject
{
    SSSQLiteDatabase *_database;
}

- (void)_dispatchBlockAsync:(id)arg1;
- (void)readUsingSessionBlock:(id)arg1;
- (void)readAsyncUsingSessionBlock:(id)arg1;
- (void)modifyUsingTransactionBlock:(id)arg1;
- (void)modifyAsyncUsingTransactionBlock:(id)arg1;
- (void)dealloc;
- (id)initReadOnly;
- (id)init;
- (id)_initReadOnly:(BOOL)arg1;

@end

