/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "SSXPCCoding.h"

@class NSDate, NSDictionary;

@interface SSLookupResponse : NSObject <SSXPCCoding>
{
    NSDate *_expirationDate;
    NSDictionary *_response;
}

@property(copy, nonatomic) NSDate *expirationDate; // @synthesize expirationDate=_expirationDate;
- (id)initWithXPCEncoding:(id)arg1;
- (id)copyXPCEncoding;
@property(readonly, nonatomic) NSDictionary *responseDictionary;
- (id)valueForProperty:(id)arg1;
- (void)dealloc;
- (id)initWithResponseDictionary:(id)arg1;

@end

