/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol _VKStyle <NSObject>
- (void)takeFromStyleProperties:(id)arg1 atZoom:(unsigned int)arg2;
- (void)takeFromZoomInvariantProperties:(id)arg1;
@end

