/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <VectorKit/VGLRealisticFadeProgram.h>

__attribute__((visibility("hidden")))
@interface VGLCasingShadowProgram : VGLRealisticFadeProgram
{
    float _ramp;
    int _uRamp;
}

+ (id)program;
@property(nonatomic) float ramp; // @synthesize ramp=_ramp;
- (id)init;

@end

