/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <VectorKit/VGLSingleTexturedMesh.h>

@class VGLTexture;

__attribute__((visibility("hidden")))
@interface VGLDualTexturedMesh : VGLSingleTexturedMesh
{
    VGLTexture *_secondTexture;
}

@property(retain, nonatomic) VGLTexture *secondTexture; // @synthesize secondTexture=_secondTexture;
- (void)drawTrianglesWithContext:(id)arg1;
- (void)dealloc;

@end

