/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class VGLFontAtlas, VGLFontGlyphCache;

__attribute__((visibility("hidden")))
@interface VGLFontManager : NSObject
{
    VGLFontAtlas *_fontAtlas;
    VGLFontGlyphCache *_glyphCache;
}

+ (id)sharedManager;
- (struct __CTFont *)referenceFontForFontKey:(id)arg1;
- (void)didReceiveMemoryWarning:(id)arg1;
- (void)_activeTileGroupDidChange:(id)arg1;
- (void)_purgeFontData;
- (id)glyphCache;
- (id)fontAtlas;
- (void)dealloc;
- (id)init;

@end

