/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class VGLFontTexture;

__attribute__((visibility("hidden")))
@interface VGLFontAtlasPage : NSObject
{
    struct VGLFontAtlasCell *_cellStorage;
    struct VGLFontAtlasCell **_freeCells;
    struct VGLFontAtlasCell **_pendingCells;
    int _freeCellCount;
    int _pendingCellCount;
    VGLFontTexture *_texture;
}

- (void)bindWithContext:(id)arg1;
- (int)numCellsInUse;
- (int)flushCells:(int)arg1;
- (void)freeCell:(struct VGLFontAtlasCell *)arg1;
- (struct VGLFontAtlasCell *)allocCell;
- (void)dealloc;
- (id)initWithPageNumber:(int)arg1;

@end

