/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <VectorKit/VGLTexture.h>

@class VGLTexturePool;

__attribute__((visibility("hidden")))
@interface VGLPooledTexture : VGLTexture
{
    VGLTexturePool *_pool;
}

- (BOOL)loadTexture;
- (void)dealloc;
- (id)initWithSize:(struct CGSize)arg1 token:(int)arg2 pool:(id)arg3;

@end

