/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <VectorKit/VGLUncompressedTexture.h>

__attribute__((visibility("hidden")))
@interface VGLRasterTexture : VGLUncompressedTexture
{
    int _mode;
}

- (BOOL)decodeTexture;
- (id)initWithData:(id)arg1 loadImmediately:(BOOL)arg2 mode:(int)arg3;

@end

