/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class VGLContext;

__attribute__((visibility("hidden")))
@interface VGLShader : NSObject
{
    int token;
    VGLContext *context;
}

@property(nonatomic) VGLContext *context; // @synthesize context;
@property(readonly, nonatomic) int token; // @synthesize token;
- (void)printShaderInfoLog;
- (BOOL)status:(unsigned int)arg1;
- (void)dealloc;
- (id)initWithName:(id)arg1 shaderType:(unsigned int)arg2;

@end

