/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface VKConsoleView : UIView
{
    UILabel *_label;
}

- (void)updateConsole:(id)arg1 map:(id)arg2;
- (void)dealloc;
- (id)init;
- (void)setFrame:(struct CGRect)arg1;
- (float)getRecommendedFrameHeight;

@end

