/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMapTable;

__attribute__((visibility("hidden")))
@interface VKIntObjectMap : NSObject
{
    NSMapTable *_mapTable;
}

- (void)setObject:(id)arg1 forKey:(int)arg2;
- (id)objectForKey:(int)arg1;
- (void)dealloc;
- (id)init;

@end

