/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface VKLabelFeaturePool : NSObject
{
    struct LabelFeatureArray<vk::LabelFeatureRoad> *_roads;
    struct LabelFeatureArray<vk::LabelFeaturePoint> *_points;
    struct LabelFeatureArray<vk::LabelFeaturePolygon> *_polygons;
}

- (void)removeDeadFeatures;
- (unsigned int)getFeatures:(struct LabelFeature **)arg1 forTile:(id)arg2 ofType:(int)arg3;
- (unsigned int)maximumFeatureCountForTile:(id)arg1 ofType:(int)arg2;
- (void)forEachFeature:(id)arg1;
- (void)reset;
- (void)dealloc;
- (id)init;

@end

