/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <VectorKit/VKTile.h>

@class GEOVoltaireRasterTileTrafficData, VKIntObjectMap;

__attribute__((visibility("hidden")))
@interface VKRasterTrafficTile : VKTile
{
    GEOVoltaireRasterTileTrafficData *_modelTile;
    VKIntObjectMap *_roadMeshes;
    VKIntObjectMap *_capMeshes;
}

- (void)dealloc;
- (void)_buildMeshes;
- (id)capMeshForSpeed:(int)arg1;
- (id)roadMeshForSpeed:(int)arg1;
- (id)initWithKey:(const struct VKTileKey *)arg1 downloadKey:(const struct _GEOTileKey *)arg2 trafficData:(id)arg3;

@end

