/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMapTable, NSMutableDictionary, VKPShieldPack;

__attribute__((visibility("hidden")))
@interface VKShieldAtlas : NSObject
{
    NSMutableDictionary *_shieldDict;
    NSMapTable *_atlasToImages;
    VKPShieldPack *_shieldPack;
}

- (id)artworkForShieldIdentifier:(id)arg1 textLength:(unsigned int)arg2 contentScale:(float)arg3 extraScale:(float)arg4 mode:(int)arg5;
- (void)purge;
- (void)dealloc;
- (id)initWithShieldPack:(id)arg1;

@end

