/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <VectorKit/VKMapTileModel.h>

__attribute__((visibility("hidden")))
@interface VKVectorMapModel : VKMapTileModel
{
}

+ (BOOL)reloadOnActiveTileGroupChange;
+ (BOOL)reloadOnStylesheetChange;
- (void)layoutScene:(id)arg1 withContext:(id)arg2;
- (BOOL)wantsCategorizedSourceTiles;
- (unsigned int)mapLayerPosition;

@end

