/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <SAObjects/SABaseClientBoundCommand.h>

#import "SADomainObjectCommand.h"

@class NSURL, SADomainObject;

@interface SADomainObjectCreate : SABaseClientBoundCommand <SADomainObjectCommand>
{
}

+ (id)domainObjectCreateWithDictionary:(id)arg1 context:(id)arg2;
+ (id)domainObjectCreate;
- (BOOL)requiresResponse;
@property(retain, nonatomic) SADomainObject *object;
@property(copy, nonatomic) NSURL *targetAppId;
- (id)encodedClassName;
- (id)groupIdentifier;

@end

