/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <SAObjects/SAUISnippetInteraction.h>

@interface SAUIConfirmSnippet : SAUISnippetInteraction
{
}

+ (id)confirmSnippetWithDictionary:(id)arg1 context:(id)arg2;
+ (id)confirmSnippet;
- (id)encodedClassName;
- (id)groupIdentifier;

@end

