/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol GEOTileDecoder <NSObject>
- (id)decodeTile:(id)arg1 forKey:(const struct _GEOTileKey *)arg2;
- (BOOL)canDecodeTile:(const struct _GEOTileKey *)arg1 quickly:(char *)arg2;
@end

