/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSData;

__attribute__((visibility("hidden")))
@interface GEOVoltaireRasterTileImageData : NSObject
{
    NSData *_data;
}

+ (id)createWithData:(id)arg1;
- (struct CGImage *)newImage;
- (void)dealloc;
- (id)initWithData:(id)arg1;

@end

