/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <iPodUI/IUStoreCompletionListViewController.h>

#import "IUAlbumOfferTableFooterViewDelegate.h"

@interface IUAlbumSongListViewController : IUStoreCompletionListViewController <IUAlbumOfferTableFooterViewDelegate>
{
}

+ (Class)tableViewCellClass;
- (BOOL)_footerShouldDrawInAlternateStyle;
- (void)albumOfferTableFooterView:(id)arg1 showItemsInOffer:(id)arg2;
- (BOOL)hideActionRowsOnAppear;
- (void)updateFooterView;
- (id)newOfferTableFooterViewWithStoreCompletionOffering:(id)arg1;
- (BOOL)_shouldShowOfferButtonOrLabelForOffering:(id)arg1;

@end

