/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol IUFoldingTransitionDelegate <NSObject>
- (void)foldingTransitionDidStop:(id)arg1 finished:(BOOL)arg2;
@end

