/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol IUiPadSeasonOfferTableFooterViewDelegate <NSObject>
- (void)seasonOfferTableFooterView:(id)arg1 showItemsInOffer:(id)arg2;
- (void)seasonOfferTableFooterView:(id)arg1 didChangeToOfferVariant:(int)arg2;
@end

