/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class MPAVController;

@protocol MPAVControllerNode <NSObject>
@property(retain, nonatomic) MPAVController *player;
- (void)unlockPlayer;
- (void)lockPlayer;
@end

