/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MPVideoTransferViewController <NSObject>
- (id)videoView;
- (void)displayVideoView;

@optional
@property(nonatomic) BOOL inhibitOverlay;
- (void)showOverlayAnimated:(BOOL)arg1;
@end

