/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "CoreDAVSubmittable.h"

@class NSSet;

@protocol CoreDAVContainerMultiGetSubmittable <CoreDAVSubmittable>
@property(nonatomic) BOOL shouldIgnoreResponseErrors;
@property(readonly, nonatomic) NSSet *parsedContents;
@property(readonly, nonatomic) NSSet *missingURLs;
@end

