/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <WebCore/DOMCSSRule.h>

@class DOMCSSStyleDeclaration, NSString;

__attribute__((visibility("hidden")))
@interface DOMCSSStyleRule : DOMCSSRule
{
}

@property(readonly) DOMCSSStyleDeclaration *style;
@property(copy) NSString *selectorText;

@end

