/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <WebCore/DOMObject.h>

__attribute__((visibility("hidden")))
@interface DOMDOMTokenList : DOMObject
{
}

- (BOOL)toggle:(id)arg1;
- (void)remove:(id)arg1;
- (void)add:(id)arg1;
- (BOOL)contains:(id)arg1;
- (id)item:(unsigned int)arg1;
@property(readonly) unsigned int length;
- (void)finalize;
- (void)dealloc;

@end

