/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface WebScriptObjectPrivate : NSObject
{
    struct JSObject *imp;
    struct RootObject *rootObject;
    struct RootObject *originRootObject;
    BOOL isCreatedByDOMWrapper;
}

@end

