/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, SUTableDataSource;

@protocol SUDownloadsChildViewController <NSObject>
@property(retain, nonatomic) NSArray *scriptButtons;
@property(retain, nonatomic) SUTableDataSource *dataSource;
- (id)visibleDownloadCellForDownload:(id)arg1;
- (void)reloadData;
- (void)reloadDownloadCellForDownload:(id)arg1;
@end

