/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <iTunesStoreUI/SULockoutViewController.h>

@interface SUNetworkLockoutViewController : SULockoutViewController
{
}

- (void)_reloadUserInterface;
- (void)loadView;
- (void)setSection:(id)arg1;
- (void)setLocalizationBundle:(id)arg1;
- (id)init;

@end

