/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <iTunesStoreUI/SUScriptViewControllerNativeObject.h>

#import "SUMessageEntryViewControllerDelegate.h"

@interface SUScriptMessageEntryViewControllerNativeObject : SUScriptViewControllerNativeObject <SUMessageEntryViewControllerDelegate>
{
}

- (void)messageEntryViewControllerDidChange:(id)arg1;
- (BOOL)messageEntryViewController:(id)arg1 shouldSendMessage:(id)arg2;
- (void)setupNativeObject;
- (void)destroyNativeObject;

@end

