/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <iTunesStoreUI/SURotationController.h>

@interface SUWebViewRotationController : SURotationController
{
}

- (void)prepareToRotateToInterfaceOrientation:(int)arg1;
- (void)finishRotationFromInterfaceOrientation:(int)arg1;

@end

