/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface PCPersistentIdentifiers : NSObject
{
}

+ (int)pidFromMatchingIdentifer:(id)arg1;
+ (id)processNamePidAndStringIdentifier:(id)arg1;
+ (id)processNameAndPidIdentifier;
+ (id)_processNamePrefix;
+ (unsigned long long)hostUniqueIdentifier;

@end

