/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <FTServices/FTiMessagePeerMessage.h>

#import "NSCopying.h"

@interface FTiMessageGenericCommandMessage : FTiMessagePeerMessage <NSCopying>
{
}

- (int)command;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

