/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <YouTube/YTVideoDataSource.h>

@class NSString;

@interface YTSubscriptionsVideoDataSource : YTVideoDataSource
{
    NSString *_subscriptionURL;
    BOOL _requiresAuth;
}

- (void)reloadData;
- (void)setSubscriptionURL:(id)arg1 requiresAuthentication:(BOOL)arg2;

@end

